kind: Service
apiVersion: v1 
metadata:
  name: ix-interface
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: ix-interface
  ports:
    - port: 80
      nodePort: 31234
  type: NodePort