apiVersion: v1
kind: ConfigMap
metadata:
  name: ix-kratos-configmap
  namespace: {{ .Values.global.namespace }}
data:
  kratos.yml: |
    version: v0.10.1

    dsn: memory

    serve:
      public:
        base_url: http://localhost:4433/
        cors:
          enabled: true
      admin:
        base_url: http://localhost:4434/

    selfservice:
      default_browser_return_url: "http://localhost:80/docs"

    log:
      level: debug
      format: text
      leak_sensitive_values: true

    secrets:
      cookie:
        - ORANOS-CRATOS-COOKIE-HASH
      cipher:
        - 0RANOS-CIPH3R-H4SH-32-CH4R-LONG*

    ciphers:
      algorithm: xchacha20-poly1305

    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8

    identity:
      default_schema_id: xapp
      schemas:
        - id: xapp
          url: file:///etc/config/xapp.schema.json

    courier:
      smtp:
        connection_uri: smtps://#
  xapp.schema.json: |
    {
      "$id": "http://mydomain.com/schemas/v2/customer.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "xApp",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "xapp_name": {
              "type": "string",
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                }
              }
            },
            "relations": {
              "type": "array"
            }
          }
        }
      },
      "additionalProperties": false
    }