apiVersion: v1
kind: PersistentVolume
metadata:
  name: ix-redis-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ix-redis-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ix-redis-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
