apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  keyfile-replicaset-init.sh: |
    #!/bin/bash
    set -e

    KEYFILE=/init/keyfile

    # Generate the keyfile if it doesn't exist.
    if [ ! -f "$KEYFILE" ]; then
      echo "Keyfile not found. Generating..."
      openssl rand -base64 756 > "$KEYFILE"
      chmod 400 "$KEYFILE"
    fi

    # Start mongod in the background.
    echo "Starting mongod..."
    mongod --replSet rs0 --bind_ip_all --port 27017 --keyFile "$KEYFILE" &
    MONGOD_PID=$!

    # Wait until mongod is accepting connections.
    until mongosh --host $MONGODB_HOST --eval 'quit(0)' &>/dev/null; do
        echo "Waiting for mongod to start..."
        sleep 5
    done

    echo "mongod started."

    # Check if the replica set is already initiated.
    # (You might improve this check based on your environment.)
    INIT_STATUS=$(mongosh --host $MONGODB_HOST --quiet --eval "rs.status().ok" 2>/dev/null || echo "0")
    if [ "$INIT_STATUS" != "1" ]; then
      echo "Replica set not yet initiated. Initiating..."
      mongosh --host $MONGODB_HOST -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin <<EOF
    rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "$MONGODB_HOST" }
      ]
    })
    EOF
    else
      echo "Replica set already initiated."
    fi

    # Bring mongod process to the foreground.
    wait $MONGOD_PID
