apiVersion: v1
kind: PersistentVolume
metadata:
  name: ix-mongodb-init-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ix-mongo-init"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ix-mongodb-init-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
