apiVersion: apps/v1
kind: Deployment
metadata:
  name: ix-mongodb
spec:
  selector:
    matchLabels:
      app: ix-mongodb
  template:
    metadata:
      labels:
        app: ix-mongodb
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
            - mountPath: /init
              name: mongodb-init
          env:
            - name: MONGODB_HOST
              value: {{ .Values.mongodb.host }}
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ix-mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ix-mongodb-secret
                  key: password

      restartPolicy: Always
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: ix-mongodb-data-pvc
        - name: mongodb-init
          persistentVolumeClaim:
            claimName: ix-mongodb-init-pvc