apiVersion: v1
kind: Secret
metadata:
  name: ix-mongodb-secret
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: secret
  connstr: mongodb://root:secret@ix-mongodb/?directConnection=true