apiVersion: apps/v1
kind: Deployment
metadata:
  name: ix-mongodb
spec:
  selector:
    matchLabels:
      app: ix-mongodb
  template:
    metadata:
      labels:
        app: ix-mongodb
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 1001:1001 /bitnami/mongodb/data/db']
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /bitnami/mongodb/data/db
              name: mongodb-data
      containers:
        - name: mongodb
          image: bitnami/mongodb:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /bitnami/mongodb/data/db
              name: mongodb-data
          env:
            - name: MONGODB_REPLICA_SET_MODE
              value: "primary"
            - name: MONGODB_REPLICA_SET_NAME
              value: "rs0"
            - name: MONGODB_PORT_NUMBER
              value: "27017"
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: {{ .Values.global.mongodb.host }}
            - name: MONGODB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: ix-mongodb-secret
                  key: username
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ix-mongodb-secret
                  key: password
            - name: MONGODB_REPLICA_SET_KEY
              valueFrom:
                secretKeyRef:
                  name: ix-mongodb-secret
                  key: replicasetkey

      restartPolicy: Always
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: ix-mongodb-data-pvc
