name: ix-interface
description: Framework enabling RIC-to-RIC communication.
version: 1.0.0
apiVersion: v1
keywords:
  - ix-interface

dependencies:
  - name: ix-mongodb
    repository: file://charts/ix-mongodb
    condition: ix-mongodb.enabled
  - name: ix-mysql
    repository: file://charts/ix-mysql
    condition: ix-mysql.enabled