apiVersion: v1
kind: Secret
metadata:
  name: ix-mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password: secret
  hydradsn: mysql://root:secret@tcp(ix-mysql)/hydra?max_conns=20&max_idle_conns=4
  kratosdsn: mysql://root:secret@tcp(ix-mysql)/kratos?max_conns=20&max_idle_conns=4